spring:
  application:
    name: config
  profiles:
    active: native
  config:
    server:
      native:
        search-locations: C:\Users\USER\Spring Projects\Microservice-Project\Config\src\main\resources\configs

server:
  port: 8888



#eureka:
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
