spring:
  application:
    name: school-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/msnetwork
    password: 123

  jpa:
    hibernate.ddl-auto:  update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888


server:
  port: 0

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

application:
  config:
    students-url: http://STUDENT-SERVICE/students